# Generated by Django 4.2.1 on 2023-06-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_number', models.CharField(max_length=20)),
                ('delivery_date', models.DateField()),
                ('time', models.TimeField()),
                ('cyclist_name', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
