# Generated by Django 4.2.1 on 2023-06-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('grocery_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('expiry_date', models.DateField()),
                ('stocked_date', models.DateField()),
                ('brand', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
