# Generated by Django 4.2.3 on 2023-08-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Add_to_cart', '0002_initial'),
        ('delivery', '0001_initial'),
        ('client', '0002_remove_client_date_of_birth'),
        ('odermanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odermanage',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='odermanage',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='odermanage',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='odermanage',
            name='order_items',
        ),
        migrations.RemoveField(
            model_name='odermanage',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='odermanage',
            name='order_total',
        ),
        migrations.RemoveField(
            model_name='odermanage',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='odermanage',
            name='Add_to_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Add_to_cart.add_to_cart'),
        ),
        migrations.AddField(
            model_name='odermanage',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='odermanage',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='odermanage',
            name='name',
            field=models.CharField(default='Default Name', max_length=32),
        ),
        migrations.AddField(
            model_name='odermanage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='odermanage',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
