# Generated by Django 4.2.1 on 2023-06-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_quantity', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('vendor_id', models.IntegerField()),
                ('date_added', models.DateField()),
            ],
        ),
    ]
