# Generated by Django 4.2.3 on 2023-07-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventorry', '0001_initial'),
        ('Add_to_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='product',
            field=models.ManyToManyField(to='inventorry.product'),
        ),
    ]
