# Generated by Django 4.2.1 on 2023-06-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100)),
                ('grocery_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('expiry_date', models.DateField()),
                ('stocked_date', models.DateField()),
                ('brand', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
